version: "3"
services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: magento
    volumes:
      - db:/var/lib/mysql

  app:
    image: magento:2.3.2
    build:
      context: ./
      args:
        MAGENTO_MARKET_USER: ${MAGENTO_MARKET_USER}
        MAGENTO_MARKET_PASS: ${MAGENTO_MARKET_PASS}
    volumes:
      - ./app/code:/var/www/magento/app/code:cached
    ports:
      - "80:8080"
    depends_on:
      - db

volumes:
  db:
