version: "3"
services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: magento
    volumes:
      - db-data:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql

  app:
    build: ./
    image: magento2-app
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html:cached
      - ./logs/apache2:/var/log/apache2
    links:
      - db
    depends_on:
      - db

volumes:
  db-data:
