version: "3"
services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: magento
    volumes:
      - db:/var/lib/mysql

  app:
    build: ./
    image: magento2-app
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html:cached
    links:
      - db
    depends_on:
      - db

volumes:
  db:
